import { lstat, readFile } from "node:fs/promises";
import { join } from "node:path";
import process from "node:process";
import { createInterface } from "node:readline";

const REST_BASE = "http://127.0.0.1:4329";
const LOCAL_APP_DATA = (process.env.LOCALAPPDATA ?? "").trim();
const TARGET_REF = /^android-[a-f0-9]{16}$/u;
const PACKAGE = /^[A-Za-z][A-Za-z0-9_]*(?:\.[A-Za-z][A-Za-z0-9_]*)+$/u;
const NODE_REF = /^[a-f0-9]{32}$/u;
const UI_ACTIONS = new Set(["click", "scroll-down", "scroll-up"]);
const GAME_ACTIONS = new Set(["tap", "swipe", "key"]);
const GAME_KEYS = new Set(["dpad-up","dpad-down","dpad-left","dpad-right","dpad-center","enter","space","escape","back","button-a","button-b","button-x","button-y","button-l1","button-r1","button-start","button-select"]);
const CWD_ROOT = "gitrepos";
const CWD_RELATIVE = "evavo-android-device-bridge";

const common = {
  targetRef: { type: "string", pattern: "^android-[a-f0-9]{16}$" },
  packageName: { type: "string", pattern: "^[A-Za-z][A-Za-z0-9_]*(?:\\.[A-Za-z][A-Za-z0-9_]*)+$" },
};

const TOOLS = Object.freeze([
  { name:"evavo_android_app_status",description:"Inspect one installed Android app and running state.",inputSchema:{type:"object",additionalProperties:false,required:["targetRef","packageName"],properties:common}},
  { name:"evavo_android_app_launch",description:"Launch one already installed Android app by package.",inputSchema:{type:"object",additionalProperties:false,required:["targetRef","packageName"],properties:common}},
  { name:"evavo_android_app_stop",description:"Force-stop one installed Android app by package.",inputSchema:{type:"object",additionalProperties:false,required:["targetRef","packageName"],properties:common}},
  { name:"evavo_android_app_diagnostics",description:"Return bounded package crash/ANR/native-crash counts and running state without returning raw logcat.",inputSchema:{type:"object",additionalProperties:false,required:["targetRef","packageName"],properties:{...common,lines:{type:"integer",minimum:1,maximum:10000}}}},
  { name:"evavo_android_app_ui_snapshot",description:"Read a privacy-bounded fresh UI hierarchy for a running foreground package.",inputSchema:{type:"object",additionalProperties:false,required:["targetRef","packageName"],properties:common}},
  { name:"evavo_android_app_ui_action",description:"Perform one confirmed fresh-node click or scroll within the foreground app package.",inputSchema:{type:"object",additionalProperties:false,required:["targetRef","packageName","nodeRef","action"],properties:{...common,nodeRef:{type:"string",pattern:"^[a-f0-9]{32}$"},action:{enum:[...UI_ACTIONS]}}}},
  { name:"evavo_android_game_input",description:"Perform one confirmed foreground-package-confined normalized tap/swipe or allowlisted game key. No arbitrary shell, text or keycodes.",inputSchema:{type:"object",additionalProperties:false,required:["targetRef","packageName","action"],properties:{...common,action:{enum:[...GAME_ACTIONS]},x:{type:"number",minimum:0,maximum:1},y:{type:"number",minimum:0,maximum:1},x2:{type:"number",minimum:0,maximum:1},y2:{type:"number",minimum:0,maximum:1},durationMs:{type:"integer",minimum:50,maximum:2000},key:{enum:[...GAME_KEYS]}}}},
  { name:"evavo_android_app_clear_data",description:"Clear private data for one verified non-system installed app. System/indeterminate packages are protected.",inputSchema:{type:"object",additionalProperties:false,required:["targetRef","packageName"],properties:common}},
  { name:"evavo_android_app_uninstall",description:"Uninstall one verified non-system installed app and its private data. System/indeterminate packages are protected.",inputSchema:{type:"object",additionalProperties:false,required:["targetRef","packageName"],properties:common}},
]);

function asObject(value){if(!value||typeof value!=="object"||Array.isArray(value))throw new Error("arguments must be an object");return value;}
async function readJsonFile(file,min,max){const stat=await lstat(file);if(!stat.isFile()||stat.isSymbolicLink()||stat.size<min||stat.size>max)throw new Error("local credential projection failed file admission");return asObject(JSON.parse(await readFile(file,"utf8")));}
async function loadOperatorToken(){if(!LOCAL_APP_DATA)throw new Error("LOCALAPPDATA is required");try{const doc=await readJsonFile(join(LOCAL_APP_DATA,"EVAVO","LocalAgentRest043","operator-token.json"),32,8192);const token=typeof doc.token==="string"?doc.token.trim():"";if(doc.schemaVersion===1&&doc.kind==="evavo-local-agent-rest-operator-credential-v1"&&doc.operatorExecEnabled===true&&token.length>=32)return{token,source:"same-user-operator-credential-projection"};}catch{}if((process.env.EVAVO_LOCAL_AGENT_REST_OPERATOR_EXEC??"").trim()!=="1")throw new Error("Local Agent operator execution is not explicitly enabled");const token=(process.env.EVAVO_LOCAL_AGENT_REST_OPERATOR_TOKEN??"").trim();if(token.length<32)throw new Error("Local Agent operator credential is unavailable");return{token,source:"process-environment"};}
function validateBase(args){const targetRef=String(args.targetRef??"").trim(),packageName=String(args.packageName??"").trim();if(!TARGET_REF.test(targetRef))throw new Error("invalid targetRef");if(!PACKAGE.test(packageName))throw new Error("invalid packageName");return{targetRef,packageName};}
function coordinate(value,label){const n=Number(value);if(!Number.isFinite(n)||n<0||n>1)throw new Error(`${label} must be between 0 and 1`);return String(n);}
async function post(command,timeoutSeconds=60){const credential=await loadOperatorToken();let response;try{response=await fetch(`${REST_BASE}/v1/operator/execute`,{method:"POST",headers:{"Content-Type":"application/json","X-EVAVO-Local-Agent-Token":credential.token},body:JSON.stringify({commandType:"cmd",command,cwdRoot:CWD_ROOT,cwdRelative:CWD_RELATIVE,timeoutSeconds}),signal:AbortSignal.timeout((timeoutSeconds+15)*1000),cache:"no-store"});}catch{throw new Error("Local Agent Android app request did not return; outcome is unknown and was not retried");}let body;try{body=asObject(await response.json());}catch{throw new Error("Local Agent REST returned invalid JSON");}if(!response.ok||body.kind!=="evavo-local-agent-rest-operator-exec-v1"||body.operatorAuthority!==true||body.shellParameterUsed!==false||body.ok!==true)throw new Error("Android app operator execution failed or returned an invalid receipt");let value;try{value=asObject(JSON.parse(String(body.stdout??"").trim()));}catch{throw new Error("Android app bridge returned invalid JSON");}return{...value,executor:{schema:"evavo.android-app-mcp-executor.v1",loopbackOnly:true,fixedCommandSurface:true,credentialValuesReturned:false,physicalWorkstationPathReturned:false,commandTextAcceptedFromCaller:false,operatorCredentialSource:credential.source}};}

async function callTool(name,raw){const args=raw===undefined?{}:asObject(raw);const{targetRef,packageName}=validateBase(args);if(name==="evavo_android_app_status")return post(`node src\\app-lifecycle-cli.mjs status --target ${targetRef} --package ${packageName} --json`);if(name==="evavo_android_app_launch")return post(`node src\\cli.mjs launch --target ${targetRef} --package ${packageName} --json`);if(name==="evavo_android_app_stop")return post(`node src\\cli.mjs stop --target ${targetRef} --package ${packageName} --json`);if(name==="evavo_android_app_diagnostics"){const lines=args.lines===undefined?4000:Number(args.lines);if(!Number.isInteger(lines)||lines<1||lines>10000)throw new Error("lines is invalid");return post(`node src\\app-diagnostics-cli.mjs --target ${targetRef} --package ${packageName} --lines ${lines} --json`,90);}if(name==="evavo_android_app_ui_snapshot")return post(`node src\\cli.mjs ui-snapshot --target ${targetRef} --package ${packageName} --json`,90);if(name==="evavo_android_app_ui_action"){const nodeRef=String(args.nodeRef??"").trim(),action=String(args.action??"").trim();if(!NODE_REF.test(nodeRef)||!UI_ACTIONS.has(action))throw new Error("UI action arguments are invalid");return post(`node src\\cli.mjs ui-action --target ${targetRef} --package ${packageName} --node ${nodeRef} --action ${action} --confirm INTERACT_WITH_ANDROID_APP_UI --json`,90);}if(name==="evavo_android_game_input"){const action=String(args.action??"").trim();if(!GAME_ACTIONS.has(action))throw new Error("game action is invalid");let command=`node src\\cli.mjs game-input --target ${targetRef} --package ${packageName} --action ${action}`;if(action==="tap")command+=` --x ${coordinate(args.x,"x")} --y ${coordinate(args.y,"y")}`;else if(action==="swipe"){const duration=args.durationMs===undefined?250:Number(args.durationMs);if(!Number.isInteger(duration)||duration<50||duration>2000)throw new Error("durationMs is invalid");command+=` --x ${coordinate(args.x,"x")} --y ${coordinate(args.y,"y")} --x2 ${coordinate(args.x2,"x2")} --y2 ${coordinate(args.y2,"y2")} --duration-ms ${duration}`;}else{const key=String(args.key??"").trim();if(!GAME_KEYS.has(key))throw new Error("game key is invalid");command+=` --key ${key}`;}return post(`${command} --confirm INTERACT_WITH_ANDROID_GAME_SURFACE --json`,90);}if(name==="evavo_android_app_clear_data")return post(`node src\\app-lifecycle-cli.mjs clear-data --target ${targetRef} --package ${packageName} --confirm CLEAR_USER_ANDROID_APP_DATA --json`,90);if(name==="evavo_android_app_uninstall")return post(`node src\\app-lifecycle-cli.mjs uninstall --target ${targetRef} --package ${packageName} --confirm UNINSTALL_USER_ANDROID_APP --json`,180);throw new Error(`unknown tool: ${name}`);}

const result=(id,value)=>({jsonrpc:"2.0",id:id??null,result:value}),error=(id,code,message)=>({jsonrpc:"2.0",id:id??null,error:{code,message}});const input=createInterface({input:process.stdin,crlfDelay:Infinity}),write=(value)=>process.stdout.write(`${JSON.stringify(value)}\n`);
for await(const line of input){if(!line.trim())continue;let request;try{request=JSON.parse(line);}catch{write(error(null,-32700,"Parse error"));continue;}if(request.jsonrpc!=="2.0"||typeof request.method!=="string"){write(error(request.id,-32600,"Invalid request"));continue;}try{if(request.method==="notifications/initialized")continue;if(request.method==="ping")write(result(request.id,{}));else if(request.method==="initialize")write(result(request.id,{protocolVersion:"2024-11-05",capabilities:{tools:{listChanged:false}},serverInfo:{name:"evavo-android-app-mcp",version:"1.0.0"}}));else if(request.method==="tools/list")write(result(request.id,{tools:TOOLS}));else if(request.method==="tools/call"){const params=asObject(request.params),value=await callTool(String(params.name??""),params.arguments);write(result(request.id,{content:[{type:"text",text:JSON.stringify(value,null,2)}],isError:false}));}else write(error(request.id,-32601,"Method not found"));}catch(caught){const message=caught instanceof Error?caught.message:"Unknown error";write(result(request.id,{content:[{type:"text",text:JSON.stringify({ok:false,error:message,credentialValuesReturned:false,physicalPathsReturned:false})}],isError:true}));}}
